package migrate

import (
	"fmt"
	"strings"
	"time"

	"github.com/tidylogic/db-diff/internal/diff"
	"github.com/tidylogic/db-diff/internal/schema"
)

// Generate produces DDL SQL from a DiffResult.
//
// direction:
//   - "apply_to_target": generate DDL to apply to TARGET, making it match source (propagate source → target)
//   - "apply_to_source": generate DDL to apply to SOURCE, making it match target (propagate target → source)
//
// dialect: "mysql" | "postgres"
func Generate(result *diff.DiffResult, direction, dialect string) (string, error) {
	if direction != "apply_to_target" && direction != "apply_to_source" {
		return "", fmt.Errorf("invalid direction %q: must be \"apply_to_target\" or \"apply_to_source\"", direction)
	}

	var sb strings.Builder

	// Header comment
	src, tgt := result.SourceName, result.TargetName
	if direction == "apply_to_source" {
		src, tgt = tgt, src
	}
	fmt.Fprintf(&sb, "-- Generated by db-diff: %s → %s  (%s)\n", src, tgt, time.Now().Format(time.RFC3339))
	fmt.Fprintf(&sb, "-- Dialect: %s\n", dialect)
	fmt.Fprintf(&sb, "-- Direction: %s\n\n", direction)

	for _, td := range result.Tables {
		stmts, err := tableStmts(td, direction, dialect)
		if err != nil {
			return "", err
		}
		if len(stmts) > 0 {
			fmt.Fprintf(&sb, "-- TABLE: %s\n", td.Name)
			for _, s := range stmts {
				fmt.Fprintf(&sb, "%s;\n", s)
			}
			fmt.Fprintln(&sb)
		}
	}

	for _, vd := range result.Views {
		stmts := viewStmts(vd, direction, dialect)
		if len(stmts) > 0 {
			fmt.Fprintf(&sb, "-- VIEW: %s\n", vd.Name)
			for _, s := range stmts {
				fmt.Fprintf(&sb, "%s;\n", s)
			}
			fmt.Fprintln(&sb)
		}
	}

	return sb.String(), nil
}

// tableStmts returns DDL statements for a single TableDiff.
func tableStmts(td diff.TableDiff, direction, dialect string) ([]string, error) {
	// Determine effective change from the caller's perspective.
	// apply_to_target propagates source → target, so Added/Removed are inverted
	// relative to the diff (which uses target-centric terminology).
	change := td.Change
	if direction == "apply_to_target" {
		change = invertChange(change)
	}

	var stmts []string

	switch change {
	case diff.Added:
		// Build a proper CREATE TABLE from the column data stored in the diff.
		// Falls back to a placeholder comment only for old diffs with no column data.
		createStmts := buildCreateTableStmts(td, dialect)
		if len(createStmts) == 0 {
			stmts = append(stmts, fmt.Sprintf("-- CREATE TABLE %s  (full DDL not available — regenerate diff with a newer version)", td.Name))
		} else {
			stmts = append(stmts, createStmts...)
		}

	case diff.Removed:
		stmts = append(stmts, fmt.Sprintf("DROP TABLE %s", quoteIdent(td.Name, dialect)))

	case diff.Modified:
		for _, cd := range td.Columns {
			colChange := cd.Change
			if direction == "apply_to_target" {
				colChange = invertChange(colChange)
			}
			stmt, err := columnStmt(td.Name, cd, colChange, direction, dialect)
			if err != nil {
				return nil, err
			}
			if stmt != "" {
				stmts = append(stmts, stmt)
			}
		}

		for _, id := range td.Indexes {
			idxChange := id.Change
			if direction == "apply_to_target" {
				idxChange = invertChange(idxChange)
			}
			s := indexStmt(td.Name, id, idxChange, direction, dialect)
			if s != "" {
				stmts = append(stmts, s)
			}
		}

		for _, cd := range td.Constraints {
			cChange := cd.Change
			if direction == "apply_to_target" {
				cChange = invertChange(cChange)
			}
			s := constraintStmt(td.Name, cd, cChange, direction, dialect)
			if s != "" {
				stmts = append(stmts, s)
			}
		}
	}

	return stmts, nil
}

func columnStmt(table string, cd diff.ColumnDiff, change diff.ChangeType, direction, dialect string) (string, error) {
	t := quoteIdent(table, dialect)
	col := quoteIdent(cd.Name, dialect)

	// Pick the column definition to use.
	// For apply_to_target the change has already been inverted, so an
	// originally-Removed column arrives here as Added; its definition lives
	// in cd.Source (not cd.Target, which is nil).
	var colDef *schema.Column
	switch change {
	case diff.Added:
		colDef = cd.Target
		if direction == "apply_to_target" {
			colDef = cd.Source
		}
	case diff.Removed:
		return fmt.Sprintf("ALTER TABLE %s DROP COLUMN %s", t, col), nil
	case diff.Modified:
		colDef = cd.Target
		if direction == "apply_to_target" {
			colDef = cd.Source
		}
	}

	if colDef == nil {
		return "", nil
	}

	typeDef := colDef.RawType
	nullStr := " NOT NULL"
	if colDef.Nullable {
		nullStr = " NULL"
	}
	defStr := ""
	if colDef.Default != nil {
		defStr = " DEFAULT " + *colDef.Default
	}
	colSpec := fmt.Sprintf("%s%s%s", typeDef, nullStr, defStr)

	switch dialect {
	case "mysql":
		switch change {
		case diff.Added:
			return fmt.Sprintf("ALTER TABLE %s ADD COLUMN %s %s", t, col, colSpec), nil
		case diff.Modified:
			return fmt.Sprintf("ALTER TABLE %s MODIFY COLUMN %s %s", t, col, colSpec), nil
		}
	case "postgres":
		switch change {
		case diff.Added:
			return fmt.Sprintf("ALTER TABLE %s ADD COLUMN %s %s", t, col, colSpec), nil
		case diff.Modified:
			stmts := []string{}
			if cd.Source != nil && cd.Target != nil && cd.Source.RawType != cd.Target.RawType {
				stmts = append(stmts, fmt.Sprintf("ALTER TABLE %s ALTER COLUMN %s TYPE %s", t, col, typeDef))
			}
			if cd.Source != nil && cd.Target != nil && cd.Source.Nullable != cd.Target.Nullable {
				if colDef.Nullable {
					stmts = append(stmts, fmt.Sprintf("ALTER TABLE %s ALTER COLUMN %s DROP NOT NULL", t, col))
				} else {
					stmts = append(stmts, fmt.Sprintf("ALTER TABLE %s ALTER COLUMN %s SET NOT NULL", t, col))
				}
			}
			if cd.Source != nil && cd.Target != nil && !ptrStrEq(cd.Source.Default, cd.Target.Default) {
				if colDef.Default != nil {
					stmts = append(stmts, fmt.Sprintf("ALTER TABLE %s ALTER COLUMN %s SET DEFAULT %s", t, col, *colDef.Default))
				} else {
					stmts = append(stmts, fmt.Sprintf("ALTER TABLE %s ALTER COLUMN %s DROP DEFAULT", t, col))
				}
			}
			return strings.Join(stmts, ";\n"), nil
		}
	}
	return "", nil
}

func indexStmt(table string, id diff.IndexDiff, change diff.ChangeType, direction, dialect string) string {
	var idx *schema.Index
	switch change {
	case diff.Added:
		// After inversion, an originally-Removed index has its def in id.Source.
		idx = id.Target
		if idx == nil {
			idx = id.Source
		}
	case diff.Removed:
		// After inversion, an originally-Added index has its def in id.Target.
		idx = id.Source
		if idx == nil {
			idx = id.Target
		}
	case diff.Modified:
		// Drop old version, create new version — pick which is "old" by direction.
		if direction == "apply_to_target" {
			// Applying to target: drop target's version, create source's version.
			return dropIndexStmt(table, id.Target, dialect) + ";\n" + createIndexStmt(table, id.Source, dialect)
		}
		// Applying to source: drop source's version, create target's version.
		return dropIndexStmt(table, id.Source, dialect) + ";\n" + createIndexStmt(table, id.Target, dialect)
	}

	if idx == nil {
		return ""
	}

	switch change {
	case diff.Added:
		return createIndexStmt(table, idx, dialect)
	case diff.Removed:
		return dropIndexStmt(table, idx, dialect)
	}
	return ""
}

func createIndexStmt(table string, idx *schema.Index, dialect string) string {
	if idx == nil {
		return ""
	}
	unique := ""
	if idx.Unique && !idx.IsPrimary {
		unique = "UNIQUE "
	}
	cols := make([]string, len(idx.Columns))
	for i, c := range idx.Columns {
		cols[i] = quoteIdent(c, dialect)
	}
	return fmt.Sprintf("CREATE %sINDEX %s ON %s (%s)",
		unique, quoteIdent(idx.Name, dialect), quoteIdent(table, dialect), strings.Join(cols, ", "))
}

func dropIndexStmt(table string, idx *schema.Index, dialect string) string {
	if idx == nil {
		return ""
	}
	switch dialect {
	case "mysql":
		return fmt.Sprintf("ALTER TABLE %s DROP INDEX %s", quoteIdent(table, dialect), quoteIdent(idx.Name, dialect))
	default: // postgres
		return fmt.Sprintf("DROP INDEX %s", quoteIdent(idx.Name, dialect))
	}
}

func constraintStmt(table string, cd diff.ConstraintDiff, change diff.ChangeType, direction, dialect string) string {
	t := quoteIdent(table, dialect)

	switch change {
	case diff.Added:
		// After inversion, an originally-Removed constraint has its def in cd.Source.
		c := cd.Target
		if c == nil {
			c = cd.Source
		}
		if c == nil {
			return ""
		}
		return addConstraintSQL(t, c, dialect)
	case diff.Removed:
		// After inversion, an originally-Added constraint has its def in cd.Target.
		c := cd.Source
		if c == nil {
			c = cd.Target
		}
		if c == nil {
			return ""
		}
		return fmt.Sprintf("ALTER TABLE %s DROP CONSTRAINT %s", t, quoteIdent(c.Name, dialect))
	case diff.Modified:
		// Drop old version, create new version — pick which is "old" by direction.
		if direction == "apply_to_target" {
			// Applying to target: drop target's version, create source's version.
			stmts := []string{}
			if cd.Target != nil {
				stmts = append(stmts, fmt.Sprintf("ALTER TABLE %s DROP CONSTRAINT %s", t, quoteIdent(cd.Target.Name, dialect)))
			}
			if cd.Source != nil {
				stmts = append(stmts, addConstraintSQL(t, cd.Source, dialect))
			}
			return strings.Join(stmts, ";\n")
		}
		// Applying to source: drop source's version, create target's version.
		stmts := []string{}
		if cd.Source != nil {
			stmts = append(stmts, fmt.Sprintf("ALTER TABLE %s DROP CONSTRAINT %s", t, quoteIdent(cd.Source.Name, dialect)))
		}
		if cd.Target != nil {
			stmts = append(stmts, addConstraintSQL(t, cd.Target, dialect))
		}
		return strings.Join(stmts, ";\n")
	}
	return ""
}

func addConstraintSQL(table string, c *schema.Constraint, dialect string) string {
	cols := make([]string, len(c.Columns))
	for i, col := range c.Columns {
		cols[i] = quoteIdent(col, dialect)
	}
	switch c.Type {
	case "FOREIGN KEY":
		refCols := make([]string, len(c.RefColumns))
		for i, rc := range c.RefColumns {
			refCols[i] = quoteIdent(rc, dialect)
		}
		return fmt.Sprintf("ALTER TABLE %s ADD CONSTRAINT %s FOREIGN KEY (%s) REFERENCES %s (%s)",
			table, quoteIdent(c.Name, dialect), strings.Join(cols, ", "),
			quoteIdent(c.RefTable, dialect), strings.Join(refCols, ", "))
	case "UNIQUE":
		return fmt.Sprintf("ALTER TABLE %s ADD CONSTRAINT %s UNIQUE (%s)",
			table, quoteIdent(c.Name, dialect), strings.Join(cols, ", "))
	default:
		return fmt.Sprintf("ALTER TABLE %s ADD CONSTRAINT %s %s (%s)",
			table, quoteIdent(c.Name, dialect), c.Type, strings.Join(cols, ", "))
	}
}

func viewStmts(vd diff.ViewDiff, direction, dialect string) []string {
	change := vd.Change
	if direction == "apply_to_target" {
		change = invertChange(change)
	}

	switch change {
	case diff.Added:
		// After inversion, an originally-Removed view has its def in vd.Source.
		def := vd.Target
		if def == nil {
			def = vd.Source
		}
		if def == nil {
			return nil
		}
		return []string{fmt.Sprintf("CREATE VIEW %s AS\n%s", quoteIdent(vd.Name, dialect), def.Definition)}
	case diff.Removed:
		return []string{fmt.Sprintf("DROP VIEW %s", quoteIdent(vd.Name, dialect))}
	case diff.Modified:
		// Pick which definition to recreate based on direction.
		var tgt *schema.View
		if direction == "apply_to_target" {
			tgt = vd.Source // propagate source def to target
		} else {
			tgt = vd.Target // propagate target def to source
		}
		if tgt == nil {
			return nil
		}
		return []string{
			fmt.Sprintf("DROP VIEW IF EXISTS %s", quoteIdent(vd.Name, dialect)),
			fmt.Sprintf("CREATE VIEW %s AS\n%s", quoteIdent(vd.Name, dialect), tgt.Definition),
		}
	}
	return nil
}

// buildCreateTableStmts produces a CREATE TABLE statement (plus separate
// CREATE INDEX and ALTER TABLE ADD CONSTRAINT statements) from the column data
// embedded in an Added TableDiff. For an inverted Removed table the column
// definitions live in cd.Source; for a naturally Added table they live in
// cd.Target. We use a nil-safe fallback so both cases are handled uniformly.
//
// Returns nil when no column data is available (old diff format without schema
// snapshots), so the caller can fall back to a placeholder comment.
func buildCreateTableStmts(td diff.TableDiff, dialect string) []string {
	if len(td.Columns) == 0 {
		return nil
	}

	t := quoteIdent(td.Name, dialect)
	var colParts []string

	for _, cd := range td.Columns {
		c := cd.Target
		if c == nil {
			c = cd.Source
		}
		if c == nil {
			continue
		}
		nullStr := " NOT NULL"
		if c.Nullable {
			nullStr = " NULL"
		}
		defStr := ""
		if c.Default != nil {
			defStr = " DEFAULT " + *c.Default
		}
		colParts = append(colParts, fmt.Sprintf("  %s %s%s%s",
			quoteIdent(c.Name, dialect), c.RawType, nullStr, defStr))
	}

	if len(colParts) == 0 {
		return nil
	}

	// Inline PRIMARY KEY clause — check Constraints first, then Indexes.
	pkAdded := false
	for _, cd := range td.Constraints {
		c := cd.Target
		if c == nil {
			c = cd.Source
		}
		if c == nil || c.Type != "PRIMARY KEY" {
			continue
		}
		cols := make([]string, len(c.Columns))
		for i, col := range c.Columns {
			cols[i] = quoteIdent(col, dialect)
		}
		colParts = append(colParts, fmt.Sprintf("  PRIMARY KEY (%s)", strings.Join(cols, ", ")))
		pkAdded = true
		break
	}
	if !pkAdded {
		for _, id := range td.Indexes {
			idx := id.Target
			if idx == nil {
				idx = id.Source
			}
			if idx == nil || !idx.IsPrimary {
				continue
			}
			cols := make([]string, len(idx.Columns))
			for i, col := range idx.Columns {
				cols[i] = quoteIdent(col, dialect)
			}
			colParts = append(colParts, fmt.Sprintf("  PRIMARY KEY (%s)", strings.Join(cols, ", ")))
			break
		}
	}

	var stmts []string
	stmts = append(stmts, fmt.Sprintf("CREATE TABLE %s (\n%s\n)", t, strings.Join(colParts, ",\n")))

	// Non-PK indexes as separate CREATE INDEX statements.
	for _, id := range td.Indexes {
		idx := id.Target
		if idx == nil {
			idx = id.Source
		}
		if idx == nil || idx.IsPrimary {
			continue
		}
		stmts = append(stmts, createIndexStmt(td.Name, idx, dialect))
	}

	// Non-PK constraints as separate ALTER TABLE ADD CONSTRAINT statements.
	for _, cd := range td.Constraints {
		c := cd.Target
		if c == nil {
			c = cd.Source
		}
		if c == nil || c.Type == "PRIMARY KEY" {
			continue
		}
		stmts = append(stmts, addConstraintSQL(t, c, dialect))
	}

	return stmts
}

// invertChange flips Added↔Removed; Modified stays Modified.
func invertChange(c diff.ChangeType) diff.ChangeType {
	switch c {
	case diff.Added:
		return diff.Removed
	case diff.Removed:
		return diff.Added
	}
	return c
}

// quoteIdent wraps an identifier in the appropriate dialect quote character.
func quoteIdent(name, dialect string) string {
	switch dialect {
	case "postgres":
		return `"` + strings.ReplaceAll(name, `"`, `""`) + `"`
	default: // mysql and others
		return "`" + strings.ReplaceAll(name, "`", "``") + "`"
	}
}

// ── Selection / GenerateFiltered ──────────────────────────────────────────────

// Selection describes which items from a DiffResult to include when generating
// migration SQL. For modified tables, an absent key in Columns/Indexes/Constraints
// means "include all items for that table".
type Selection struct {
	Tables      []string            `json:"tables"`
	Columns     map[string][]string `json:"columns"`
	Indexes     map[string][]string `json:"indexes"`
	Constraints map[string][]string `json:"constraints"`
	Views       []string            `json:"views"`
}

// GenerateFiltered generates migration SQL for only the items named in sel.
// It builds a filtered copy of result and delegates to Generate.
func GenerateFiltered(result *diff.DiffResult, sel Selection, direction, dialect string) (string, error) {
	tableSet := toStringSet(sel.Tables)
	viewSet := toStringSet(sel.Views)

	filtered := &diff.DiffResult{
		SourceName: result.SourceName,
		TargetName: result.TargetName,
	}

	for _, td := range result.Tables {
		if !tableSet[td.Name] {
			continue
		}
		if td.Change != diff.Modified {
			// Added/Removed tables: include as-is when selected.
			filtered.Tables = append(filtered.Tables, td)
			continue
		}
		// Modified table: filter sub-items.
		colSet := toStringSet(sel.Columns[td.Name])
		idxSet := toStringSet(sel.Indexes[td.Name])
		conSet := toStringSet(sel.Constraints[td.Name])

		ftd := diff.TableDiff{Name: td.Name, Change: td.Change}
		for _, cd := range td.Columns {
			if len(colSet) == 0 || colSet[cd.Name] {
				ftd.Columns = append(ftd.Columns, cd)
			}
		}
		for _, id := range td.Indexes {
			if len(idxSet) == 0 || idxSet[id.Name] {
				ftd.Indexes = append(ftd.Indexes, id)
			}
		}
		for _, cd := range td.Constraints {
			if len(conSet) == 0 || conSet[cd.Name] {
				ftd.Constraints = append(ftd.Constraints, cd)
			}
		}
		filtered.Tables = append(filtered.Tables, ftd)
	}

	for _, vd := range result.Views {
		if viewSet[vd.Name] {
			filtered.Views = append(filtered.Views, vd)
		}
	}

	return Generate(filtered, direction, dialect)
}

func toStringSet(ss []string) map[string]bool {
	m := make(map[string]bool, len(ss))
	for _, s := range ss {
		m[s] = true
	}
	return m
}

func ptrStrEq(a, b *string) bool {
	if a == nil && b == nil {
		return true
	}
	if a == nil || b == nil {
		return false
	}
	return *a == *b
}
